name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Install deny
        run: cargo install cargo-deny
      - name: Lint
        run: cargo fmt --all -- --check
      - name: Run cargo deny check
        run: cargo deny check licenses
      - name: Build
        run: cross build --target ${{ matrix.target }} --release
      - name: Run tests
        run: cross test --target ${{ matrix.target }} --release

