name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Run cargo deny check
        run: cargo deny check all
      - name: Create Release License
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
      - name: Download source code tarball
        run: |
          curl -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" -L -o source.tar.gz https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.ref_name }}

      - name: Generate SHA-256 checksum
        run: |
          sha256sum source.tar.gz > source.sha256

      - name: Upload Release source checksum
        uses: softprops/action-gh-release@v1
        with:
          files: |
            source.sha256
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"

  release:
    needs: check-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: linux
            arch: x86_64
            release_postfix: ""
          - target: aarch64-unknown-linux-gnu
            os: linux
            arch: aarch64
            release_postfix: ""
          - target: x86_64-pc-windows-gnu
            os: windowz
            arch: x86_64
            release_postfix: ".exe"

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: cross build --target ${{ matrix.target }} --release
      - name: Archive binaries
        run: |
          mkdir -p target/release/bin
          cp target/${{ matrix.target }}/release/openapiv3-filter${{ matrix.release_postfix }} target/release/bin/openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.release_postfix }}
          tar czvf openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C target/release/bin openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.release_postfix }}
        shell: bash
      - name: Calculate checksums
        run: |
          sha256sum "openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz" > "openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz.sha256"
          echo "checksums: \n$(ls openapiv3-filter-*.sha256)"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
  macos-release:
    #Disable macos release builds
    if: false
    name: macos-release
    needs: check-release
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            os: macos
            target: x86_64-apple-darwin
            release_postfix: ""
          - arch: aarch64
            os: macos
            target: aarch64-apple-darwin
            release_postfix: ""
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          brew update || brew update-reset
          brew install coreutils
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
      - name: Archive binaries
        run: |
          mkdir -p target/release/bin
          cp target/${{ matrix.target }}/release/openapiv3-filter${{ matrix.release_postfix }} target/release/bin/openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.release_postfix }}
          tar czvf openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C target/release/bin openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.release_postfix }}
        shell: bash
      - name: Calculate checksums
        run: |
          sha256sum "openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz" > "openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz.sha256"
          echo "checksums: \n$(ls openapiv3-filter-*.sha256)"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            openapiv3-filter-${{ matrix.os }}-${{ matrix.arch }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
